=== prateekakhanna/myrepo/TimeShift_POC/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by ï»¿user user (Amdocs Management UK) -->
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Field">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">						
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="IdField">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Values" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string">				
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Template">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IdField" />
				<xs:element ref="TimeShiftTemplate" />
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="active" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:boolean">
						<xs:enumeration value="true"></xs:enumeration>
						<xs:enumeration value="false"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="epcqueryname" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="displayheader" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="TemplateList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Template" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TimeShiftTemplate">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UniqueFieldList" />
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="continousLogic" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:boolean">
						<xs:enumeration value="true"></xs:enumeration>
						<xs:enumeration value="false"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="displayfield" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="UniqueFieldList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Value" type="xs:string"/>
	<xs:element name="Values">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== prateekakhanna/myrepo/TimeShift_POC/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<TemplateList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
	<Template name="BillingDiscount" active="false" epcqueryname="getBillingDiscountWithTimeShiftStatusReady"
	displayheader="Template Name,ID,TimeShift Template Xpath,Flow,Execution Date,BillingRateGUId,Field Name,Date,TimeShift Date">
		<IdField name="DiscountId">
			<Values>
				<Value/>
			</Values>
		</IdField>
		<TimeShiftTemplate name="BillingRate" xpath="BillingDiscountRateList.BillingRate" continousLogic="true" displayfield="BillingRateGUId">
			<UniqueFieldList>
				<Field name="ApplicableForRatePlan"/>
				<Field name="BillingFrequency"/>
			</UniqueFieldList>
		</TimeShiftTemplate>
	</Template>
	<Template name="BillingElement" active="false" epcqueryname="getBillingElementWithTimeShiftStatus"
		displayheader="Template Name,ID,TimeShift Template Xpath,Flow,Execution Date,BillingRecurringChargeGUId,Field Name,Date,TimeShift Date">
		<IdField name="ElementId">
			<Values>
				<Value/>
			</Values>
		</IdField>
		<TimeShiftTemplate name="BillingRecurringCharge" xpath="BillingRecurringCharge" continousLogic="true" displayfield="BillingRecurringChargeGUId">
			<UniqueFieldList>
				<Field name="ApplicableRateClassRef"/>
				<Field name="BillingFrequency"/>
			</UniqueFieldList>
		</TimeShiftTemplate>
	</Template>
	<Template name="ProductOffering" active="true" epcqueryname="getProductOfferingByTimeShiftStatus"
		displayheader="Template Name,ID,TimeShift Template Xpath,Flow,Execution Date,PriceSettingId,Field Name,Date,TimeShift Date">
		<IdField name="ProductOfferingId">
			<Values>
				<Value/>
			</Values>
		</IdField>
		<TimeShiftTemplate name="ProductOfferingPriceSetting" xpath="CompositeProductChoiceList.CompositeProductOfferingChoice.CompositeProductOffering.ProductOfferingPriceSetting" 
			continousLogic="true" displayfield="PriceSettingId">
			<UniqueFieldList>
				<Field name="VATDefinitionRef"/>
			</UniqueFieldList>
		</TimeShiftTemplate>
	</Template>
</TemplateList>
